name: tic_tac_toe
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  provider: ^6.0.0
  delayed_display: ^2.0.0
  audioplayers: ^0.20.0
  auto_size_text: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/mine.jpg
    - images/satoru.jpg
    - images/Win.png
    - images/Draw.png
    - assets/

  fonts:
    - family: Paytone
      fonts:
        - asset: fonts/PaytoneOne-Regular.ttf
    - family: Carter
      fonts:
        - asset: fonts/CarterOne-Regular.ttf




